function parseCsv(value = '') {
  return String(value || '').split(',').map((entry) => entry.trim()).filter(Boolean);
}

export function readBackendRuntime(env = process.env) {
  const nodeEnv = env.NODE_ENV || 'development';
  const isProd = nodeEnv === 'production';
  const mode = env.CUSTOM_BACKEND_MODE || (isProd ? 'postgres' : 'memory');
  const redisUrl = env.REDIS_URL || env.EVENT_BUS_REDIS_URL || env.RATE_LIMIT_REDIS_URL || '';
  const rateLimitMode = env.RATE_LIMIT_MODE || (redisUrl ? 'redis' : 'memory');
  const eventBusMode = env.EVENT_BUS_MODE || (redisUrl && isProd ? 'redis' : 'memory');
  const workerStoreMode = env.WORKER_STORE_MODE || (mode === 'postgres' ? 'postgres' : 'memory');
  const jobStoreMode = env.JOB_STORE_MODE || (mode === 'postgres' ? 'postgres' : 'memory');
  const eventReplayStoreMode = env.EVENT_REPLAY_STORE_MODE || (mode === 'postgres' ? 'postgres' : 'memory');

  return {
    port: Number(env.PORT || 8787),
    nodeEnv,
    isProduction: isProd,
    mode,
    databaseUrl: env.DATABASE_URL || '',
    redisUrl,
    rateLimitRedisUrl: env.RATE_LIMIT_REDIS_URL || redisUrl,
    rateLimitMode,
    eventBusMode,
    workerStoreMode,
    jobStoreMode,
    eventReplayStoreMode,
    sessionSecret: env.SESSION_SECRET || '',
    sessionCookieName: env.SESSION_COOKIE_NAME || 'uare_session',
    sessionCookieDomain: env.SESSION_COOKIE_DOMAIN || '',
    sessionCookieSameSite: env.SESSION_COOKIE_SAMESITE || (isProd ? 'Lax' : 'Lax'),
    sessionCookieSecure: env.SESSION_COOKIE_SECURE === 'true' || isProd,
    sessionCookieMaxAgeSec: Math.max(Number(env.SESSION_COOKIE_MAX_AGE_SEC || 60 * 60 * 24 * 14), 300),
    sessionAbsoluteLifetimeSec: Math.max(Number(env.SESSION_ABSOLUTE_LIFETIME_SEC || 60 * 60 * 24 * 30), 300),
    sessionRollingEnabled: env.SESSION_ROLLING_ENABLED !== 'false',
    allowDevHeaderAuth: env.ALLOW_DEV_HEADER_AUTH === 'true' ? true : !isProd,
    jwtIssuer: env.JWT_ISSUER || '',
    jwtAudience: env.JWT_AUDIENCE || '',
    jwtJwksUrl: env.JWT_JWKS_URL || '',
    enableRequestLogs: env.ENABLE_REQUEST_LOGS !== 'false',
    appBaseUrl: env.APP_BASE_URL || '',
    corsAllowedOrigins: parseCsv(env.CORS_ALLOWED_ORIGINS || ''),
    trustedOrigins: parseCsv(env.TRUSTED_ORIGINS || env.CORS_ALLOWED_ORIGINS || env.APP_BASE_URL || ''),
    trustProxy: env.TRUST_PROXY === 'true' || isProd,
    contentSecurityPolicy: env.CONTENT_SECURITY_POLICY || "default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline' https://unpkg.com https://cdn.jsdelivr.net; connect-src 'self' https:; font-src 'self' data: https://fonts.gstatic.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",
    requestBodyLimit: env.REQUEST_BODY_LIMIT || '2mb',
    rateLimitWindowMs: Math.max(Number(env.RATE_LIMIT_WINDOW_MS || 60000), 1000),
    rateLimitMax: Math.max(Number(env.RATE_LIMIT_MAX || 180), 1),
    authRateLimitWindowMs: Math.max(Number(env.AUTH_RATE_LIMIT_WINDOW_MS || env.RATE_LIMIT_WINDOW_MS || 60000), 1000),
    authRateLimitMax: Math.max(Number(env.AUTH_RATE_LIMIT_MAX || 30), 1),
    gracefulShutdownTimeoutMs: Math.max(Number(env.GRACEFUL_SHUTDOWN_TIMEOUT_MS || 10000), 1000),
    exposeErrors: env.EXPOSE_ERRORS === 'true' || !isProd,
    opsMetricsToken: env.OPS_METRICS_TOKEN || '',
    publicHealthDetails: env.PUBLIC_HEALTH_DETAILS === 'true' || (!isProd && env.PUBLIC_HEALTH_DETAILS !== 'false'),
    auditStoreFile: env.AUDIT_STORE_FILE || `${env.DATA_ROOT_DIR || './data'}/audit-events.json`,
    auditStoreMaxEntries: Math.max(Number(env.AUDIT_STORE_MAX_ENTRIES || 5000), 100),
    idempotencyStoreFile: env.IDEMPOTENCY_STORE_FILE || `${env.DATA_ROOT_DIR || './data'}/idempotency-store.json`,
    idempotencyStoreMaxEntries: Math.max(Number(env.IDEMPOTENCY_STORE_MAX_ENTRIES || 5000), 100),
    idempotencyTtlMs: Math.max(Number(env.IDEMPOTENCY_TTL_MS || 24 * 60 * 60 * 1000), 60_000),
    requiredProdVars: parseCsv(env.REQUIRED_PROD_VARS || 'SESSION_SECRET,APP_BASE_URL,DATABASE_URL,REDIS_URL,STRIPE_SECRET_KEY,STRIPE_WEBHOOK_SECRET'),
    cadKernelEnabled: env.CAD_KERNEL_ENABLED === 'true',
    cadGuardrailOverrideToken: env.CAD_GUARDRAIL_OVERRIDE_TOKEN || '',
    cadPythonBin: env.CAD_PYTHON_BIN || env.PYTHON || '',
    cadPythonCandidates: parseCsv(env.CAD_PYTHON_CANDIDATES || ''),
    cadKernelEngine: env.CAD_KERNEL_ENGINE || 'cadquery',
    occPythonBin: env.OCC_PYTHON_BIN || env.CAD_PYTHON_BIN || env.PYTHON || '',
    occPythonCandidates: parseCsv(env.OCC_PYTHON_CANDIDATES || env.CAD_PYTHON_CANDIDATES || ''),
    ngspiceBin: env.NGSPICE_BIN || 'ngspice',
    artifactBaseUrl: env.ARTIFACT_BASE_URL || '',
    artifactStorageMode: env.ARTIFACT_STORAGE_MODE || 'local',
    objectStorageMirrorDir: env.OBJECT_STORAGE_MIRROR_DIR || './object_storage_mirror',
    artifactUrlMode: env.ARTIFACT_URL_MODE || 'public',
    artifactRootDir: env.ARTIFACT_ROOT_DIR || '',
    patentSearchMode: env.PATENT_SEARCH_MODE || 'memory',
    solverExecutionTarget: env.SOLVER_EXECUTION_TARGET || 'in_process',
    physicsExecutionTarget: env.PHYSICS_EXECUTION_TARGET || 'in_process',
    cadExecutionTarget: env.CAD_EXECUTION_TARGET || 'in_process',
    taskLeaseMs: Number(env.TASK_LEASE_MS || 300000),
    taskMaxAttempts: Number(env.TASK_MAX_ATTEMPTS || 3),
    taskProgressLogLimit: Number(env.TASK_PROGRESS_LOG_LIMIT || 200),
    workerContainerImage: env.WORKER_CONTAINER_IMAGE || '',
    gpuWorkerClass: env.GPU_WORKER_CLASS || '',
    autonomousWorkerEnabled: env.AUTONOMOUS_WORKER_ENABLED === 'true',
    autonomousWorkerId: env.AUTONOMOUS_WORKER_ID || '',
    autonomousWorkerPollMs: Number(env.AUTONOMOUS_WORKER_POLL_MS || 1200),
    autonomousWorkerHeartbeatMs: Number(env.AUTONOMOUS_WORKER_HEARTBEAT_MS || 2000),
    autonomousWorkerExecutionTargets: parseCsv(env.AUTONOMOUS_WORKER_EXECUTION_TARGETS || 'queued,subprocess'),
    autonomousWorkerKinds: parseCsv(env.AUTONOMOUS_WORKER_KINDS || 'solver,cad,physics'),
    autonomousWorkerConcurrency: Math.max(Number(env.AUTONOMOUS_WORKER_CONCURRENCY || 1), 1),
    workflowWatchdogEnabled: env.WORKFLOW_WATCHDOG_ENABLED === 'true',
    workflowWatchdogIntervalMs: Math.max(Number(env.WORKFLOW_WATCHDOG_INTERVAL_MS || 30000), 1000),
    workflowSweepStaleMs: Math.max(Number(env.WORKFLOW_SWEEP_STALE_MS || 120000), 1000),
    workflowSweepBatchSize: Math.max(Number(env.WORKFLOW_SWEEP_BATCH_SIZE || 50), 1),
    workflowStepMaxRetries: Math.max(Number(env.WORKFLOW_STEP_MAX_RETRIES || 2), 0),
    workflowStepLeaseMs: Math.max(Number(env.WORKFLOW_STEP_LEASE_MS || env.TASK_LEASE_MS || 300000), 1000),
    workflowParallelReadySteps: Math.max(Number(env.WORKFLOW_PARALLEL_READY_STEPS || 2), 1),
    workflowBranchMaxChildren: Math.max(Number(env.WORKFLOW_BRANCH_MAX_CHILDREN || 2), 0),
    workflowBranchMaxReopens: Math.max(Number(env.WORKFLOW_BRANCH_MAX_REOPENS || 1), 0),
    workflowBranchMinScore: Number(env.WORKFLOW_BRANCH_MIN_SCORE || 0),
    workflowTieredMaxFinalistsPerRoot: Math.max(Number(env.WORKFLOW_TIERED_MAX_FINALISTS_PER_ROOT || 1), 1),
    workflowTieredMinScoreForVerification: Number(env.WORKFLOW_TIERED_MIN_SCORE_FOR_VERIFICATION || 0),
    workflowTieredRequirePhysicsPass: env.WORKFLOW_TIERED_REQUIRE_PHYSICS_PASS !== 'false',
    workflowTieredRequireMidFidelityPass: env.WORKFLOW_TIERED_REQUIRE_MID_FIDELITY_PASS !== 'false',
    patentProviderBridgeUrl: env.PATENT_PROVIDER_BRIDGE_URL || '',
    patentProviderBridgeToken: env.PATENT_PROVIDER_BRIDGE_TOKEN || '',
    patentProviderBridgeTimeoutMs: Math.max(Number(env.PATENT_PROVIDER_BRIDGE_TIMEOUT_MS || 10000), 1000),
    patentProviderCacheTtlMs: Math.max(Number(env.PATENT_PROVIDER_CACHE_TTL_MS || 300000), 1000),
    patentProviderRateLimitPerMinute: Math.max(Number(env.PATENT_PROVIDER_RATE_LIMIT_PER_MINUTE || 30), 1),
    metricsShipUrl: env.METRICS_SHIP_URL || '',
    metricsShipToken: env.METRICS_SHIP_TOKEN || '',
    metricsShipIntervalMs: Math.max(Number(env.METRICS_SHIP_INTERVAL_MS || 15000), 1000),
    eventBusPgChannel: env.EVENT_BUS_PG_CHANNEL || 'uare_events',
    eventBusInstanceId: env.EVENT_BUS_INSTANCE_ID || '',
    eventBusRedisUrl: env.EVENT_BUS_REDIS_URL || redisUrl,
    eventBusRedisChannel: env.EVENT_BUS_REDIS_CHANNEL || 'uare_events',
    eventBusNatsServers: env.EVENT_BUS_NATS_SERVERS || '',
    eventBusNatsSubject: env.EVENT_BUS_NATS_SUBJECT || 'uare.events',
    eventReplayTable: env.EVENT_REPLAY_TABLE || 'event_replay',
    eventReplayArchiveTable: env.EVENT_REPLAY_ARCHIVE_TABLE || 'event_replay_archive',
    eventReplayMaxEntries: Math.max(Number(env.EVENT_REPLAY_MAX_ENTRIES || 2000), 100),
    eventReplayArchiveEnabled: env.EVENT_REPLAY_ARCHIVE_ENABLED !== 'false',
    eventReplayArchiveMaxEntries: Math.max(Number(env.EVENT_REPLAY_ARCHIVE_MAX_ENTRIES || 10000), 100),
    eventReplayRetentionDays: Math.max(Number(env.EVENT_REPLAY_RETENTION_DAYS || 30), 1),
    eventReplayArchiveBatchSize: Math.max(Number(env.EVENT_REPLAY_ARCHIVE_BATCH_SIZE || 500), 1),
    eventReplayArchiveIntervalMs: Math.max(Number(env.EVENT_REPLAY_ARCHIVE_INTERVAL_MS || 300000), 1000),
    fleetAnalyticsTable: env.FLEET_ANALYTICS_TABLE || 'fleet_metrics',
    billingProvider: env.BILLING_PROVIDER || 'mock',
    billingSuccessUrl: env.BILLING_SUCCESS_URL || '',
    billingCancelUrl: env.BILLING_CANCEL_URL || '',
    stripeSecretKey: env.STRIPE_SECRET_KEY || '',
    stripeWebhookSecret: env.STRIPE_WEBHOOK_SECRET || '',
    stripeWebhookToleranceSec: Math.max(Number(env.STRIPE_WEBHOOK_TOLERANCE_SEC || 300), 30),
    stripePriceMap: {
      free: env.STRIPE_PRICE_FREE || '',
      pro: env.STRIPE_PRICE_PRO || '',
      studio: env.STRIPE_PRICE_STUDIO || '',
      enterprise: env.STRIPE_PRICE_ENTERPRISE || '',
    },
    dataRootDir: env.DATA_ROOT_DIR || './data',
    productStoreFile: env.PRODUCT_STORE_FILE || `${env.DATA_ROOT_DIR || './data'}/product-store${mode === 'postgres' || isProd ? '' : `-${process.pid}`}.json`,
    projectStoreFile: env.PROJECT_STORE_FILE || `${env.DATA_ROOT_DIR || './data'}/projects${mode === 'postgres' || isProd ? '' : `-${process.pid}`}.json`,
    missionStoreFile: env.MISSION_STORE_FILE || `${env.DATA_ROOT_DIR || './data'}/missions${mode === 'postgres' || isProd ? '' : `-${process.pid}`}.json`,
  };
}
